### ISSUE TITLE
Old MacOS compatible

### ISSUE THREAD

**Issue by etunni** [Formkunft/Light-Table#4]
Could be  possible to use Light-Table under MacOS 10.5?
I saw in readme that isn't possible, perhaps some hack may be usable to use it.
Thanks!

**Comment by florianpircher** [comment]
Are you sure you use 10.5? Glyphs runs on macOS 10.11 or later.

This plugin runs on macOS 12 or later. I started the project to explore developing software with modern technologies, which is why the plugin requires a fairly recent OS version.

**Comment by etunni** [comment]
My MacOS is 10.15 !

**Comment by florianpircher** [comment]
I will have to see whether I can support macOS 11 and 10.15. About 10 percent of Glyphs users are on macOS 11 or older and that number is steadily decreasing.

Currently, I prioritize adding missing features and improving existing features of the plugin. And I guess once that is done, the usage statistics will have shifted enough to make it not worthwhile backporting the plugin to older systems.

**Comment by etunni** [comment]
Florian, don't worry!
When I update my old mac, I'll use Light-Table surely.
Thanks for support!

**Comment by florianpircher** [comment]
At this point I am fairly confident that macOS 11 and below are not realistic. macOS 12 will be the minimum OS version.
