### ISSUE TITLE
[Feature request] Update Commit window on file save

### ISSUE THREAD

**Issue by Mark2Mark** [Formkunft/Light-Table#6]
(Nice to have) Whenever I hit the save button, update the Commit window (Comparison Inspector?), so when that window is on a secondary screen, one can see the updates without the need of activating that window by clicking on it.

This might not be necessary for many, but I usually like to see my changes in the pre-stage stage. Maybe some kind of OCD 😆

**Comment by florianpircher** [comment]
Great idea that my single-monitor workflow would never have triggered!

I have a similar idea where unsaved documents are marked in some way in the files list so you don’t forget to save before committing. The two should go hand in hand.

Oh, and it’s the “Repository Window” ;)

**Comment by Mark2Mark** [comment]
Try an iPad if you have. The sidecar feature makes it a really smooth and fast (and small) secondary monitor. Nice for notes or things like the Repository Window.

**Comment by florianpircher** [comment]
I found that multi-monitor is just not for me. Not because of the lack of trying: here is my setup from 2019, a 27″ iMac next to a “Pro Display XDR”. But I keep returning to a single monitor.

![IMG_3331](https://github.com/Formkunft/Light-Table/assets/3776198/166dcd6a-9ec1-4336-bef4-0c680854827e)

**Comment by Mark2Mark** [comment]
All or nothing!
(Maybe you should stop printing out your displays and use real ones 😆🫠 Sorry for offtopicing)

**Comment by florianpircher** [comment]
Will ship in the next release.
